{{- $image := .Values.image | default dict }}
{{- $service := .Values.service | default dict }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "cloud-native-app.fullname" . }}
spec:
  {{- with .Values.deploymentStrategy }}
  strategy:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount | default 1 }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "cloud-native-app.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "cloud-native-app.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ $image.repository | default .Chart.Name }}:{{ $image.tag | default .Chart.AppVersion }}"
          ports:
            - containerPort: {{ $service.targetPort | default 8000 }}
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
