apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloud-native-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: cloud-native-app
  template:
    metadata:
      labels:
        app: cloud-native-app
    spec:
      containers:
      - name: app
        image: PLACEHOLDER_IMAGE
        ports:
        - containerPort: 8000
        env:
        - name: ENV
          value: "prod"
  