name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  id-token: write
  contents: read

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  REGION: us-central1
  GKE_CLUSTER: cloud-native-app-cluster 
  GKE_LOCATION: us-central1-a  
  IMAGE: us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/cloud-native-app/cloud-native-app

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          cd .github/workflows/cloud-native-app/App
          pip install -r requirements.txt

      - name: Run tests
        run: |
          cd .github/workflows/cloud-native-app/App
          pytest

  build-and-push:
    needs: test
    runs-on: ubuntu-latest
    permissions: # Fontos a WIF-hez!
      contents: 'read'
      id-token: 'write'
    steps:
      - uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.GCP_WIF_PROVIDER }}
          service_account: ${{ secrets.GCP_WIF_SERVICE_ACCOUNT }}

      - name: Configure Docker for Artifact Registry
        run: gcloud auth configure-docker us-central1-docker.pkg.dev --quiet

      - name: Build and push Docker image
        run: |
          cd .github/workflows/cloud-native-app/App
          # Buildelés a teljes névvel
          docker build -t "$IMAGE:$GITHUB_SHA" .
          docker tag "$IMAGE:$GITHUB_SHA" "$IMAGE:latest"
          
          docker push "$IMAGE:$GITHUB_SHA"
          docker push "$IMAGE:latest"

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.GCP_WIF_PROVIDER }}
          service_account: ${{ secrets.GCP_WIF_SERVICE_ACCOUNT }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Verify auth
        run: |
          gcloud auth list
          gcloud auth print-access-token | head -c 20

      - name: Configure Docker for GCR
        run: gcloud auth configure-docker --quiet

      - name: Build and push Docker image
        run: |
          cd .github/workflows/cloud-native-app/App

          docker build -t "$IMAGE:$GITHUB_SHA" .
          docker tag "$IMAGE:$GITHUB_SHA" "$IMAGE:latest"

          docker push "$IMAGE:$GITHUB_SHA"
          docker push "$IMAGE:latest"

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - uses: actions/checkout@v4

      
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.GCP_WIF_PROVIDER }}
          service_account: ${{ secrets.GCP_WIF_SERVICE_ACCOUNT }}

      
      - name: Get GKE credentials
        uses: google-github-actions/get-gke-credentials@v2
        with:
          cluster_name: ${{ env.GKE_CLUSTER }}
          location: ${{ env.GKE_LOCATION }}
          project_id: ${{ env.PROJECT_ID }}

      
      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: 'latest'

      
      - name: Deploy with Helm
        run: |
          helm upgrade --install cloud-native-app ./charts/cloud-native-app \
            --namespace default \
            --set image.repository=$IMAGE \
            --set image.tag=$GITHUB_SHA \
            --set service.targetPort=8000 \
            --set livenessProbe.httpGet.path=/health \
            --set readinessProbe.httpGet.path=/health \
            --wait \
            --timeout 5m